CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname      VARCHAR(50)           DEFAULT NULL,
    api_key       VARCHAR(255)          DEFAULT NULL,
    status        SMALLINT              DEFAULT 1,
    last_login_at TIMESTAMP             DEFAULT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_status ON users (status);

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.email IS '邮箱，唯一';
COMMENT ON COLUMN users.password_hash IS 'BCrypt 加密密码';
COMMENT ON COLUMN users.nickname IS '昵称';
COMMENT ON COLUMN users.api_key IS '用户自配的 DeepSeek API Key';
COMMENT ON COLUMN users.status IS '0-禁用 1-正常';
COMMENT ON COLUMN users.last_login_at IS '最后登录时间';