-- changeset offerpilot:003-target-positions
-- comment: 创建目标职位表

CREATE TABLE target_positions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    title        VARCHAR(200) NOT NULL,
    company      VARCHAR(200)          DEFAULT NULL,
    jd_text      TEXT         NOT NULL,
    location     VARCHAR(100)          DEFAULT NULL,
    salary_range VARCHAR(50)           DEFAULT NULL,
    is_default   SMALLINT              DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_target_positions_user_id ON target_positions (user_id);

COMMENT ON TABLE target_positions IS '目标职位表';
COMMENT ON COLUMN target_positions.user_id IS '所属用户';
COMMENT ON COLUMN target_positions.title IS '职位名称，如 Java高级开发工程师';
COMMENT ON COLUMN target_positions.company IS '公司名称';
COMMENT ON COLUMN target_positions.jd_text IS '职位描述全文';
COMMENT ON COLUMN target_positions.location IS '工作地点';
COMMENT ON COLUMN target_positions.salary_range IS '薪资范围';
COMMENT ON COLUMN target_positions.is_default IS '0-否 1-默认职位';

ALTER TABLE target_positions ADD FOREIGN KEY (user_id) REFERENCES users (id);