CREATE TABLE reports
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT   NOT NULL,
    resume_id           BIGINT   NOT NULL,
    position_id         BIGINT   NOT NULL,
    match_score         DECIMAL(5, 2) DEFAULT NULL,
    tech_stack_analysis JSONB         DEFAULT NULL,
    highlights          JSONB         DEFAULT NULL,
    weaknesses          JSONB         DEFAULT NULL,
    full_report         TEXT          DEFAULT NULL,
    analysis_data       TEXT          DEFAULT NULL,
    status              SMALLINT      DEFAULT 0,
    error_message       VARCHAR(500)  DEFAULT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_reports_user_id ON reports (user_id);
CREATE INDEX idx_reports_resume_id ON reports (resume_id);
CREATE INDEX idx_reports_position_id ON reports (position_id);
CREATE INDEX idx_reports_status ON reports (status);

COMMENT ON TABLE reports IS '评估报告表';
COMMENT ON COLUMN reports.match_score IS '匹配度百分比，如 72.00';
COMMENT ON COLUMN reports.tech_stack_analysis IS '技术栈分析 JSON';
COMMENT ON COLUMN reports.highlights IS '亮点提炼 JSON 数组';
COMMENT ON COLUMN reports.weaknesses IS '短板提醒 JSON 数组';
COMMENT ON COLUMN reports.full_report IS '报告原始文本';
COMMENT ON COLUMN reports.analysis_data IS '完整的 AI 分析结果 JSON，包含技能深度分析、项目评估、提升路线图等多维度信息';
COMMENT ON COLUMN reports.status IS '0-生成中 1-完成 2-失败';
COMMENT ON COLUMN reports.error_message IS '失败原因';

ALTER TABLE reports ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE reports ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);
ALTER TABLE reports ADD FOREIGN KEY (position_id) REFERENCES target_positions (id);