CREATE TABLE interview_sessions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT   NOT NULL,
    resume_id        BIGINT   NOT NULL,
    position_id      BIGINT   NOT NULL,
    current_round    SMALLINT          DEFAULT 1,
    current_question INT               DEFAULT 0,
    total_questions  INT               DEFAULT 0,
    score            JSONB             DEFAULT NULL,
    summary          TEXT              DEFAULT NULL,
    duration_seconds INT               DEFAULT 0,
    status           SMALLINT          DEFAULT 0,
    expired_at       TIMESTAMP         DEFAULT NULL,
    started_at       TIMESTAMP         DEFAULT NULL,
    finished_at      TIMESTAMP         DEFAULT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version          INTEGER   NOT NULL DEFAULT 0
);

CREATE INDEX idx_interview_sessions_user_id ON interview_sessions (user_id);
CREATE INDEX idx_interview_sessions_status ON interview_sessions (status);
CREATE INDEX idx_interview_sessions_expired_at ON interview_sessions (expired_at);

COMMENT ON TABLE interview_sessions IS '面试会话表';
COMMENT ON COLUMN interview_sessions.current_round IS '当前轮次：1-一面 2-二面 3-三面';
COMMENT ON COLUMN interview_sessions.current_question IS '当前题目序号 0-10';
COMMENT ON COLUMN interview_sessions.total_questions IS '总回答题数';
COMMENT ON COLUMN interview_sessions.score IS '各维度评分 JSON';
COMMENT ON COLUMN interview_sessions.summary IS '面试总结文本';
COMMENT ON COLUMN interview_sessions.duration_seconds IS '面试时长(秒)';
COMMENT ON COLUMN interview_sessions.status IS '0-进行中 1-已完成 2-已过期 3-已中断';
COMMENT ON COLUMN interview_sessions.expired_at IS '过期时间(中断后+1小时)';
COMMENT ON COLUMN interview_sessions.started_at IS '面试开始时间';
COMMENT ON COLUMN interview_sessions.finished_at IS '面试结束时间';
COMMENT ON COLUMN interview_sessions.version IS '乐观锁版本号';

ALTER TABLE interview_sessions ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE interview_sessions ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);
ALTER TABLE interview_sessions ADD FOREIGN KEY (position_id) REFERENCES target_positions (id);