CREATE TABLE interview_questions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     BIGINT   NOT NULL,
    round          SMALLINT NOT NULL,
    question_index INT      NOT NULL,
    question_text  TEXT     NOT NULL,
    user_answer    TEXT              DEFAULT NULL,
    feedback       TEXT              DEFAULT NULL,
    score          DECIMAL(3, 1)     DEFAULT NULL,
    status         SMALLINT          DEFAULT 0,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version        INTEGER   NOT NULL DEFAULT 0
);

CREATE INDEX idx_interview_questions_session_id ON interview_questions (session_id);
CREATE INDEX idx_interview_questions_round ON interview_questions (round);

COMMENT ON TABLE interview_questions IS '面试题目表';
COMMENT ON COLUMN interview_questions.session_id IS '所属面试会话';
COMMENT ON COLUMN interview_questions.round IS '轮次：1-一面 2-二面 3-三面';
COMMENT ON COLUMN interview_questions.question_index IS '题号 1-10';
COMMENT ON COLUMN interview_questions.question_text IS 'AI 提出的问题';
COMMENT ON COLUMN interview_questions.user_answer IS '用户回答';
COMMENT ON COLUMN interview_questions.feedback IS 'AI 反馈';
COMMENT ON COLUMN interview_questions.score IS '本题评分 1-10';
COMMENT ON COLUMN interview_questions.status IS '0-待答 1-已答 2-已跳过';
COMMENT ON COLUMN interview_questions.version IS '乐观锁版本号';

ALTER TABLE interview_questions ADD FOREIGN KEY (session_id) REFERENCES interview_sessions (id);