CREATE TABLE chat_memory
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(100) NOT NULL,
    user_id         BIGINT                DEFAULT NULL,
    message_type    VARCHAR(20)  NOT NULL,
    content         TEXT         NOT NULL,
    metadata        JSONB                 DEFAULT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_memory_conversation_id ON chat_memory (conversation_id);
CREATE INDEX idx_chat_memory_user_id ON chat_memory (user_id);

COMMENT ON TABLE chat_memory IS 'AI 对话记忆表（每条消息一行）';
COMMENT ON COLUMN chat_memory.conversation_id IS '会话 ID（interview session ID）';
COMMENT ON COLUMN chat_memory.user_id IS '用户 ID，便于按用户查询对话记录';
COMMENT ON COLUMN chat_memory.message_type IS '消息类型：USER/ASSISTANT/SYSTEM';
COMMENT ON COLUMN chat_memory.content IS '消息内容';
COMMENT ON COLUMN chat_memory.metadata IS '消息元数据';