-- changeset offerpilot:008-knowledge_base
-- comment: 创建知识库文档表，每个文档对应一次上传（文本或文件），内容分片后索引到 pgvector

CREATE TABLE knowledge_base
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    title        VARCHAR(255) NOT NULL,
    content      TEXT,
    content_type VARCHAR(20)  NOT NULL DEFAULT 'text',
    file_url     VARCHAR(500)          DEFAULT NULL,
    chunk_count  INT                   DEFAULT 0,
    status       SMALLINT     NOT NULL DEFAULT 0,
    fail_reason  VARCHAR(500)          DEFAULT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_knowledge_base_user_id ON knowledge_base (user_id);
CREATE INDEX idx_knowledge_base_status ON knowledge_base (status);

COMMENT ON TABLE knowledge_base IS '知识库文档表';
COMMENT ON COLUMN knowledge_base.user_id IS '用户 ID';
COMMENT ON COLUMN knowledge_base.title IS '文档标题';
COMMENT ON COLUMN knowledge_base.content IS '原始文本内容（文件上传时存储解析后的文本）';
COMMENT ON COLUMN knowledge_base.content_type IS '内容类型：text/file/url';
COMMENT ON COLUMN knowledge_base.file_url IS '文件存储 URL（MinIO）';
COMMENT ON COLUMN knowledge_base.chunk_count IS '分片数量';
COMMENT ON COLUMN knowledge_base.status IS '状态：0=索引中 1=已完成 2=失败';
COMMENT ON COLUMN knowledge_base.fail_reason IS '失败原因';