CREATE TABLE assistant_conversations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(200) NOT NULL DEFAULT '新对话',
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_assistant_conversations_user_id ON assistant_conversations (user_id);
CREATE INDEX idx_assistant_conversations_updated_at ON assistant_conversations (updated_at DESC);

COMMENT ON TABLE assistant_conversations IS 'AI 小助手对话列表';
COMMENT ON COLUMN assistant_conversations.user_id IS '用户 ID';
COMMENT ON COLUMN assistant_conversations.title IS '对话标题（自动生成或默认）';
COMMENT ON COLUMN assistant_conversations.status IS '状态：ACTIVE-正常 DELETED-已删除';

ALTER TABLE assistant_conversations ADD FOREIGN KEY (user_id) REFERENCES users (id);