CREATE TABLE user_token_usage
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT   NOT NULL,
    usage_date       DATE     NOT NULL DEFAULT CURRENT_DATE,
    total_tokens     INT      NOT NULL DEFAULT 0,
    prompt_tokens    INT      NOT NULL DEFAULT 0,
    completion_tokens INT     NOT NULL DEFAULT 0,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_token_usage_user_date ON user_token_usage (user_id, usage_date);

ALTER TABLE user_token_usage ADD CONSTRAINT fk_token_usage_user FOREIGN KEY (user_id) REFERENCES users (id);

COMMENT ON TABLE user_token_usage IS '用户每日 LLM Token 用量记录';
COMMENT ON COLUMN user_token_usage.user_id IS '用户 ID';
COMMENT ON COLUMN user_token_usage.usage_date IS '用量日期';
COMMENT ON COLUMN user_token_usage.total_tokens IS '总 token 数';
COMMENT ON COLUMN user_token_usage.prompt_tokens IS '输入 token 数';
COMMENT ON COLUMN user_token_usage.completion_tokens IS '输出 token 数';